language: python
python:
  - "3.6"
#  - "3.7"
install:
  - pip install codecov
  - pip install .

before_script:
  - make testenv-start

script:
  - make test

after_success:
  - codecov

after_script:
  - make testenv-kill