language: python
python:
  - "3.6"
#  - "3.7"
install:
  - pip install .
script:
  - python test/env/bin/test_env.py build config_example.json && python unittest test/test_app.py && python test/env/bin/test_env.py kill
