class BaseStorage:
    def read(self, index, key): ...
    def write(self, index, key, record): ...
    def pop(self, index, key): ...
    def remove(self, index, key): ...

    def create_index(self, index): ...
    def drop_index(self, index): ...

    def _get_index(self, index): ...